# Generated by Django 3.1.4 on 2021-01-24 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('washapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartype', models.CharField(choices=[('SD', 'Sedan'), ('HT', 'Hatchback'), ('SP', 'Sport'), ('CP', 'Couple')], default='SD', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='washapp.washercompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
