# Generated by Django 3.1.4 on 2021-01-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0002_hirecompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirecompany',
            name='user',
        ),
    ]
