# Generated by Django 3.1.4 on 2021-01-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0003_remove_hirecompany_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirecompany',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
