# Generated by Django 3.1.4 on 2021-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0006_auto_20210129_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('type', models.CharField(choices=[('SD', 'Sedan'), ('HT', 'Hatchback'), ('SP', 'Sport'), ('CP', 'Couple')], default='SD', max_length=2)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
