# Generated by Django 3.1.4 on 2021-01-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washapp', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
